version: '3.5'

services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:2
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - '8884:8883'
    networks:
      - default
    restart: unless-stopped

networks:
  default: