apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c --replicas=1
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c --replicas=1
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto:2
          name: mosquitto-container
          ports:
            - containerPort: 1883
          resources: {}
          volumeMounts:
            - mountPath: /mosquitto/config/
              name: mosquitto-claim0
              subPath: mosquitto.conf
      restartPolicy: Always
      volumes:
        - name: mosquitto-claim0
          configMap:
            name: mosquitto-claim0
status: {}
